branch-defaults:
  master:
    environment: csc648-webapp-dev
environment-defaults:
  csc648-webapp-dev:
    branch: null
    repository: null
global:
  application_name: csc648_webapp
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.8.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
